sudo: required
services:
  - docker

before_install:
  - docker build -t conradperes/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run conradperes/react-test npm test -- --coverage

after_success:
  - docker build -t conradperes/multi-client ./client
  - docker build -t conradperes/multi-nginx ./nginx
  - docker build -t conradperes/multi-server ./server
  - docker build -t conradperes/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push conradperes/multi-client
  - docker push conradperes/multi-nginx
  - docker push conradperes/multi-server
  - docker push conradperes/multi-worker
